name: Auto Archive AC code

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  AutoArchive:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Archive directory
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.0
      - name: install procon-gardener
        run: go install github.com/togatoga/procon-gardener@latest
      - name: procon-gardener init
        run: /home/runner/go/bin/procon-gardener init
      - name: Create config.json
        run: |
          echo -e "{\"atcoder\": {\"repository_path\": \"$GITHUB_WORKSPACE\", \"user_id\": \"${{secrets.ATCODER_USERNAME}}\", \"user_email\": \"${{secrets.EMAIL}}\"}}" \
            > /home/runner/.procon-gardener/config.json
      - name: Archive AC codes
        run: /home/runner/go/bin/procon-gardener archive
      - name: git setting
        run: |
          git config --local user.email ${{secrets.EMAIL}}
          git config --local user.name ${{github.actor}}
      - name: push files
        run: |
          git push origin master
